"""add ai tables

Revision ID: 6daeea1afe9a
Revises: d7bdef458c97
Create Date: 2026-08-04 11:13:15.252463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6daeea1afe9a'
down_revision: Union[str, Sequence[str], None] = 'd7bdef458c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type_contenu', sa.String(length=100), nullable=False),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variantes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('marqueurs_a_completer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('titre_interne', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_company_id'), 'generations', ['company_id'], unique=False)
    op.create_index(op.f('ix_generations_id'), 'generations', ['id'], unique=False)
    op.create_table('audits',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('executive_id', sa.UUID(), nullable=True),
    sa.Column('score_global', sa.Integer(), nullable=False),
    sa.Column('score_entreprise', sa.Integer(), nullable=False),
    sa.Column('score_dirigeant', sa.Integer(), nullable=True),
    sa.Column('dirigeant_present', sa.Boolean(), nullable=False),
    sa.Column('score_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analyse_ia', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linkedin_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executive_id'], ['executives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_company_id'), 'audits', ['company_id'], unique=False)
    op.create_index(op.f('ix_audits_executive_id'), 'audits', ['executive_id'], unique=False)
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('critere_code', sa.String(length=100), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('priorite', sa.Enum('CRITIQUE', 'IMPORTANTE', 'OPTIMISATION', name='recommendation_priority'), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('raison', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_audit_id'), 'recommendations', ['audit_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('optimizations',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('type_element', sa.String(length=100), nullable=False),
    sa.Column('contenu_original', sa.Text(), nullable=True),
    sa.Column('variantes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variante_recommandee', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('marqueurs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faiblesses_corrigees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ameliorations_apportees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimizations_id'), 'optimizations', ['id'], unique=False)
    op.create_index(op.f('ix_optimizations_recommendation_id'), 'optimizations', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimizations_recommendation_id'), table_name='optimizations')
    op.drop_index(op.f('ix_optimizations_id'), table_name='optimizations')
    op.drop_table('optimizations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_audit_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_executive_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_company_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_generations_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_company_id'), table_name='generations')
    op.drop_table('generations')
    sa.Enum(name="recommendation_priority").drop(op.get_bind())
    # ### end Alembic commands ###
